In [1]:
import numpy as np 
print("Numpy is ready!")

Numpy is ready!

In [2]:
salary  =  np.array([2, 10, 50, 5, 6, 2, 2, 22, 8])
new_salary = salary * 2
print(new_salary)

[  4  20 100  10  12   4   4  44  16]

In [17]:
employee_salaries = np.array([
    [1000, 1200], 
    [1500, 1600],
    [2000, 2100]
])
sum_salary = my_2D_array.sum(axis=1)
print(sum_salary)
sum_salary = my_2D_array.sum(axis=0)
print(sum_salary)

[2200 3100 4100]
[4500 4900]

In [13]:
import pandas as pd

employees_data = {
    "name" : ["Ali", "Sara", "Karim"],
    "age": [28, 32, 25], 
    "salary" : [1500, 2000, 1200],
    "department" : ["IT", "HR", "IT"]
}

df_employees = pd.DataFrame(employees_data)
df_employees

    name  age  salary department
0    Ali   28    1500         IT
1   Sara   32    2000         HR
2  Karim   25    1200         IT

In [14]:
ages = df_employees["age"]
print(ages)

0    28
1    32
2    25
Name: age, dtype: int64

In [42]:
IT_employees = df_employees[df_employees["department"] == "IT"]
IT_employees

    name  age  salary department   company  bonus
0    Ali   28    1500         IT  TechCorp  150.0
2  Karim   25    1200         IT  TechCorp  120.0

In [33]:
df_employees["company"] = "TechCorp"
df_employees

    name  age  salary department   company
0    Ali   28    1500         IT  TechCorp
1   Sara   32    2000         HR  TechCorp
2  Karim   25    1200         IT  TechCorp

In [39]:
df_employees["bonus"] = df_employees["salary"] * 0.10
df_employees

    name  age  salary department   company  bonus
0    Ali   28    1500         IT  TechCorp  150.0
1   Sara   32    2000         HR  TechCorp  200.0
2  Karim   25    1200         IT  TechCorp  120.0

In [49]:
df_employees.to_csv("employees_bonus_report.csv", index=False)

In [43]:
IT_employees = df_employees[
    (df_employees["department"] == "IT") & 
    (df_employees["salary"] > 1300)
]
IT_employees

  name  age  salary department   company  bonus
0  Ali   28    1500         IT  TechCorp  150.0

In [24]:
df_employees.shape

(3, 4)

In [25]:
df_employees.dtypes

name          object
age            int64
salary         int64
department    object
dtype: object

In [26]:
df_employees.describe()

             age       salary
count   3.000000     3.000000
mean   28.333333  1566.666667
std     3.511885   404.145188
min    25.000000  1200.000000
25%    26.500000  1350.000000
50%    28.000000  1500.000000
75%    30.000000  1750.000000
max    32.000000  2000.000000

In [59]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [61]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())

df_cleaned["Embarked"] = df_cleaned["Embarked"].fillna(df_cleaned["Embarked"].mode()[0])

print(df_cleaned.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64