In [10]:
import pandas as pd

df = pd.read_csv("very_messy_dataset_2500_rows.csv")
df.head(10)

,id,name,age,city,country,department,salary,email,join_date,score
0,0.0,Ali,NaN,lyon,france,Finance,2200,NaN,2023-01-05,NaN
1,NaN,Sara,29,marseille,France,IT,2000,test@yahoo.com,05/01/2023,90
2,2.0,Omar,23,NaN,NaN,NaN,4000,test@yahoo.com,2023/01/05,100
3,3.0,mohamed,twenty,PARIS,NaN,SALES,3500,contact@outlook.com,05/01/2023,40
4,490.0,Sara,21,marseille,France,it,3500,NaN,Jan 5 2023,fifty
5,NaN,Nadia,28,paris,FRA,Sales,3000€,contact@outlook.com,NaN,NaN
6,316.0,Amina,23,paris,France,Finance,999999,contact@outlook.com,2023-01-05,40
7,7.0,Karim,24,LILLE,NaN,it,2200,contact@outlook.com,Jan 5 2023,40
8,343.0,SARA,30,NaN,France,HR,3000€,NaN,05/01/2023,30
9,236.0,Youssef,30,Lille,france,it,999999,user@gmail.com,05/01/2023,10

In [23]:
text_columns = ["city", "name", "country", "department"]

for col in text_columns:
    df[col] = df[col].str.lower().str.strip()

df.head(5)

,id,name,age,city,country,department,salary,email,join_date,score
0,0.0,ali,NaN,lyon,france,finance,2200,NaN,2023-01-05,NaN
1,NaN,sara,29,marseille,france,it,2000,test@yahoo.com,05/01/2023,90
2,2.0,omar,23,NaN,NaN,NaN,4000,test@yahoo.com,2023/01/05,100
3,3.0,mohamed,twenty,paris,NaN,sales,3500,contact@outlook.com,05/01/2023,40
4,490.0,sara,21,marseille,france,it,3500,NaN,Jan 5 2023,fifty

In [25]:
df["salary"] = df["salary"].str.replace("€", "", regex=False)
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

df["salary"].head(10)

0      2200.0
1      2000.0
2      4000.0
3      3500.0
4      3500.0
5      3000.0
6    999999.0
7      2200.0
8      3000.0
9    999999.0
Name: salary, dtype: float64

In [26]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["age"].head(10)

0     NaN
1    29.0
2    23.0
3     NaN
4    21.0
5    28.0
6    23.0
7    24.0
8    30.0
9    30.0
Name: age, dtype: float64