In [1]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_employees_data.csv')

df.head(3)

,id,name,age,city,country,department,salary,email,score
0,0.0,ali,25.0,lyon,france,finance,2200.0,unknown,50.0
1,unknown,sara,29.0,marseille,france,it,2000.0,test@yahoo.com,90.0
2,2.0,omar,23.0,unknown,unknown,unknown,4000.0,test@yahoo.com,100.0

In [17]:
df = df.drop(['id', 'email', 'name' ], axis=1, errors='ignore')
df.head(3)

    age       city  country department  salary  score
0  25.0       lyon   france    finance  2200.0   50.0
1  29.0  marseille   france         it  2000.0   90.0
2  23.0    unknown  unknown    unknown  4000.0  100.0

In [19]:
df.isnull().sum()

age            0
city          35
country        0
department    28
salary         0
score          0
dtype: int64