In [4]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_employees_data.csv')

df.head(3)

,id,name,age,city,country,department,salary,email,score
0,0.0,ali,25.0,lyon,france,finance,2200.0,unknown,50.0
1,unknown,sara,29.0,marseille,france,it,2000.0,test@yahoo.com,90.0
2,2.0,omar,23.0,unknown,unknown,unknown,4000.0,test@yahoo.com,100.0

In [5]:
df = df.drop(['id', 'email', 'name' ], axis=1, errors='ignore')
df.head(3)

    age       city  country department  salary  score
0  25.0       lyon   france    finance  2200.0   50.0
1  29.0  marseille   france         it  2000.0   90.0
2  23.0    unknown  unknown    unknown  4000.0  100.0

In [6]:
df.isnull().sum()

age            0
city          35
country        0
department    28
salary         0
score          0
dtype: int64

In [9]:
import numpy as np
df.replace('unknown', np.nan, inplace=True)
df.head(3)

    age       city country department  salary  score
0  25.0       lyon  france    finance  2200.0   50.0
1  29.0  marseille  france         it  2000.0   90.0
2  23.0        NaN     NaN        NaN  4000.0  100.0

In [10]:
df.isnull().sum()

age             0
city          270
country       529
department    340
salary          0
score           0
dtype: int64

In [13]:
print((df.isnull().sum()/ len(df))* 100)

age            0.000000
city          17.475728
country       34.239482
department    22.006472
salary         0.000000
score          0.000000
dtype: float64

In [22]:
df['country'] = df['country'].fillna("others")
df['city'] = df['city'].fillna('others')
df['department'] = df['department'].fillna(df['department'].mode()[0])
df.head(3)

    age       city country department  salary  score
0  25.0       lyon  france    finance  2200.0   50.0
1  29.0  marseille  france         it  2000.0   90.0
2  23.0     others  others      sales  4000.0  100.0

In [31]:
df.isnull().sum()

age           0
city          0
country       0
department    0
salary        0
score         0
dtype: int64

In [32]:
df_final = pd.get_dummies(df, drop_first=True)
df_final.head()

,age,salary,score,city_lyon,city_marseille,city_others,city_paris,country_others,department_hr,department_it,department_marketing,department_sales
0,25.0,2200.0,50.0,True,False,False,False,False,False,False,False,False
1,29.0,2000.0,90.0,False,True,False,False,False,False,True,False,False
2,23.0,4000.0,100.0,False,False,True,False,True,False,False,False,True
3,25.0,3500.0,40.0,False,False,False,True,True,False,False,False,True
4,21.0,3500.0,50.0,False,True,False,False,False,False,True,False,False

In [30]:
df['country'] = df['country'].replace(['fr','fra'], 'france')
df_final = pd.get_dummies(df)
df_final.head()

,age,salary,score,city_lille,city_lyon,city_marseille,city_others,city_paris,country_france,country_others,department_finance,department_hr,department_it,department_marketing,department_sales
0,25.0,2200.0,50.0,False,True,False,False,False,True,False,True,False,False,False,False
1,29.0,2000.0,90.0,False,False,True,False,False,True,False,False,False,True,False,False
2,23.0,4000.0,100.0,False,False,False,True,False,False,True,False,False,False,False,True
3,25.0,3500.0,40.0,False,False,False,False,True,False,True,False,False,False,False,True
4,21.0,3500.0,50.0,False,False,True,False,False,True,False,False,False,True,False,False